# Form implementation generated from reading ui file 'c:\Users\mikei\OneDrive\Documentos\chat-backend-python-main\interface\tela_chat.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 645)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #111b21;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #111b21;\n"
"    color: #e9edef;\n"
"}\n"
"\n"
"\n"
"\n"
"QLineEdit {\n"
"    background-color: #202c33;\n"
"    color: #e9edef;\n"
"    border: 1px solid #2a3942;\n"
"    border-radius: 10px;\n"
"    padding: 9px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00a884;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #00a884;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 9px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #06cf9c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #008069;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: #0b141a;\n"
"    color: #e9edef;\n"
"    border: 1px solid #2a3942;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #111b21;\n"
"    color: #e9edef;\n"
"    border: 1px solid #2a3942;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #2a3942;\n"
"    color: #00a884;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #111b21;\n"
"    color: #e9edef;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #111b21;\n"
"    color: #8696a0;\n"
"}\n"
"\n"
"QPushButton#btn_deletar_mensagem {\n"
"    background-color: #dc2626;\n"
"}\n"
"\n"
"QPushButton#btn_deletar_mensagem:hover {\n"
"    background-color: #ef4444;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(327, 9, 561, 591))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_logo = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_logo.setFont(font)
        self.label_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout_2.addWidget(self.label_logo)
        self.label_usuario_logado = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_usuario_logado.setFont(font)
        self.label_usuario_logado.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_usuario_logado.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_usuario_logado.setWordWrap(False)
        self.label_usuario_logado.setIndent(-1)
        self.label_usuario_logado.setObjectName("label_usuario_logado")
        self.verticalLayout_2.addWidget(self.label_usuario_logado)
        self.label_sala_atual = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_sala_atual.setFont(font)
        self.label_sala_atual.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_sala_atual.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_sala_atual.setWordWrap(False)
        self.label_sala_atual.setIndent(-1)
        self.label_sala_atual.setObjectName("label_sala_atual")
        self.verticalLayout_2.addWidget(self.label_sala_atual)
        self.label_mensagens = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_mensagens.setObjectName("label_mensagens")
        self.verticalLayout_2.addWidget(self.label_mensagens)
        self.area_mensagens = QtWidgets.QTextEdit(parent=self.layoutWidget)
        self.area_mensagens.setReadOnly(True)
        self.area_mensagens.setObjectName("area_mensagens")
        self.verticalLayout_2.addWidget(self.area_mensagens)
        self.label_mensagem = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_mensagem.setObjectName("label_mensagem")
        self.verticalLayout_2.addWidget(self.label_mensagem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_mensagem = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.input_mensagem.setObjectName("input_mensagem")
        self.horizontalLayout.addWidget(self.input_mensagem)
        self.btn_enviar = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_enviar.setObjectName("btn_enviar")
        self.horizontalLayout.addWidget(self.btn_enviar)
        self.btn_deletar_mensagem = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_deletar_mensagem.setObjectName("btn_deletar_mensagem")
        self.horizontalLayout.addWidget(self.btn_deletar_mensagem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 9, 311, 591))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_sala = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_sala.setObjectName("label_sala")
        self.verticalLayout.addWidget(self.label_sala)
        self.input_sala = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.input_sala.setObjectName("input_sala")
        self.verticalLayout.addWidget(self.input_sala)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_criar_sala = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.btn_criar_sala.setObjectName("btn_criar_sala")
        self.horizontalLayout_2.addWidget(self.btn_criar_sala)
        self.btn_listar_salas = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.btn_listar_salas.setObjectName("btn_listar_salas")
        self.horizontalLayout_2.addWidget(self.btn_listar_salas)
        self.btn_entrar_sala = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.btn_entrar_sala.setObjectName("btn_entrar_sala")
        self.horizontalLayout_2.addWidget(self.btn_entrar_sala)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_salas = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_salas.setObjectName("label_salas")
        self.verticalLayout.addWidget(self.label_salas)
        self.lista_salas = QtWidgets.QListWidget(parent=self.layoutWidget1)
        self.lista_salas.setObjectName("lista_salas")
        self.verticalLayout.addWidget(self.lista_salas)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_logo.setText(_translate("MainWindow", "ZIPZAP"))
        self.label_usuario_logado.setText(_translate("MainWindow", "Usuário:"))
        self.label_sala_atual.setText(_translate("MainWindow", "Sala:"))
        self.label_mensagens.setText(_translate("MainWindow", "Mensagens"))
        self.area_mensagens.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_mensagem.setText(_translate("MainWindow", "Mensagem"))
        self.input_mensagem.setPlaceholderText(_translate("MainWindow", "Digite sua mensagem ..."))
        self.btn_enviar.setText(_translate("MainWindow", "Enviar"))
        self.btn_deletar_mensagem.setText(_translate("MainWindow", "Apagar"))
        self.label_sala.setText(_translate("MainWindow", "Sala"))
        self.input_sala.setPlaceholderText(_translate("MainWindow", "Nome da sala"))
        self.btn_criar_sala.setText(_translate("MainWindow", "Criar Sala"))
        self.btn_listar_salas.setText(_translate("MainWindow", "Atualizar"))
        self.btn_entrar_sala.setText(_translate("MainWindow", "Entrar Sala"))
        self.label_salas.setText(_translate("MainWindow", "Salas"))
