# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 360)
        MainWindow.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #111827;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #111827;\n"
"    color: #f3f4f6;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #f3f4f6;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #1f2937;\n"
"    color: #ffffff;\n"
"    border: 2px solid #8b5cf6;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #c084fc;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #7c3aed;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8b5cf6;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: #0f172a;\n"
"    color: #e5e7eb;\n"
"    border: 2px solid #8b5cf6;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #0f172a;\n"
"    color: #e5e7eb;\n"
"    border: 2px solid #8b5cf6;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QMessageBox {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QMessageBox QLabel {\n"
"    color: black;\n"
"}\n"
"\n"
"QMessageBox QPushButton {\n"
"    background-color: #7c3aed;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setEnabled(True)
        self.label_titulo.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_titulo.setTextFormat(QtCore.Qt.PlainText)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.verticalLayout_2.addWidget(self.label_titulo)
        self.label_subtitulo = QtWidgets.QLabel(self.centralwidget)
        self.label_subtitulo.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_subtitulo.setFont(font)
        self.label_subtitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_subtitulo.setObjectName("label_subtitulo")
        self.verticalLayout_2.addWidget(self.label_subtitulo, 0, QtCore.Qt.AlignTop)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_usuario = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_usuario.setFont(font)
        self.label_usuario.setObjectName("label_usuario")
        self.verticalLayout.addWidget(self.label_usuario)
        self.input_usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.input_usuario.setObjectName("input_usuario")
        self.verticalLayout.addWidget(self.input_usuario)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout.addWidget(self.btn_login)
        self.btn_criar_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.btn_criar_usuario.setObjectName("btn_criar_usuario")
        self.horizontalLayout.addWidget(self.btn_criar_usuario)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.verticalLayout_2.addWidget(self.label_status)
        self.label_status.raise_()
        self.label_subtitulo.raise_()
        self.label_titulo.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login - Sistema de Chat"))
        self.label_titulo.setText(_translate("MainWindow", "ZIP ZAP"))
        self.label_subtitulo.setText(_translate("MainWindow", "Acesse sua conta para continuar"))
        self.label_usuario.setText(_translate("MainWindow", "Usuário"))
        self.input_usuario.setPlaceholderText(_translate("MainWindow", "Digite seu usuário"))
        self.btn_login.setText(_translate("MainWindow", "Entrar"))
        self.btn_criar_usuario.setText(_translate("MainWindow", "Criar Usuário"))
